name: Cypress Tests

on: push

jobs:
  build-app:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.CI_TOKEN }}

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          start: npm run start
          build: npm run build
          config: baseUrl=http://localhost:8080
          headed: true

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: error
