name: Cypress Tests

on: push

jobs:
  build-app:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.CI_TOKEN }}

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: build

  cypress-tests:
    needs: build-app
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.CI_TOKEN }}

      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install-command: npm install serve --global
          start: npm start
          browser: chrome
          parallel: true
          record: true
          wait-on: "http://localhost:8080"

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: error
